/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2014-10-13 19:02:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.colors;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class colrs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      colors.ColorGameBean cb = null;
      synchronized (session) {
        cb = (colors.ColorGameBean) _jspx_page_context.getAttribute("cb", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (cb == null){
          cb = new colors.ColorGameBean();
          _jspx_page_context.setAttribute("cb", cb, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("cb"), request);
      out.write("\r\n");
      out.write("\r\n");

    cb.processRequest();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=");
      out.print( cb.getColor1() );
      out.write(">\r\n");
      out.write("<font size=6 color=");
      out.print( cb.getColor2() );
      out.write(">\r\n");
      out.write("<p>\r\n");
      out.write("\r\n");
 if (cb.getHint()==true) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <p> Hint #1: Vampires prey at night!\r\n");
      out.write("    <p>  <p> Hint #2: Nancy without the n.\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
 if  (cb.getSuccess()==true) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <p> CONGRATULATIONS!!\r\n");
      out.write("    ");
 if  (cb.getHintTaken()==true) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <p> ( although I know you cheated and peeked into the hints)\r\n");
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<p> Total attempts so far: ");
      out.print( cb.getAttempts() );
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\r\n");
      out.write("<form method=POST action=colrs.jsp>\r\n");
      out.write("\r\n");
      out.write("Color #1: <input type=text name= color1 size=16>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("Color #2: <input type=text name= color2 size=16>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\r\n");
      out.write("<input type=submit name=action value=\"Submit\">\r\n");
      out.write("<input type=submit name=action value=\"Hint\">\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</font>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
